#!/bin/sh

export ES_JAVA_OPTS="${ES_JAVA_OPTS:--Xms1G -Xmx1G}"
export ES_PATH_CONF=/etc/elasticsearch

exec /usr/share/elasticsearch/bin/elasticsearch \
    -p /var/run/elasticsearch/elasticsearch.pid \
    -E path.logs=/var/log/elasticsearch \
    -E path.data=/var/lib/elasticsearch \
    -E network.host=0.0.0.0 $@
